from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

class AgentState(BaseModel):
    """
    Represents the state of an agent in the system.
    """
    messages: Annotated[list[BaseMessage], add_messages] = Field(
    default_factory=list
    )
    user_question: str = Field(..., description="The original user question that the agent will respond to.")
    curated_question:str| None = Field(default=None, description="A curated user question that the agent will use to generate a response.")
    prompt_query_context:str| None = Field(default=None, description="Detailed prompt with sql query context to be used by the agent for generating a response.")

    is_safe:Literal["Yes", "No"]| None = Field(default="No", description="Indicates whether the agent's response is safe or not. Possible values are 'Yes' or 'No'.")
    comments:str| None=Field(default=None,description="Comments for the query generated")
    generated_sql_query:str| None = Field(default=None, description="The SQL query generated by the agent based on the curated question and prompt query context.")
    sql_query_execution_result:str| None = Field(default=None, description="The result of executing the generated SQL query.")
    final_answer:str| None = Field(default=None, description="The final answer generated by the agent after processing the curated question, prompt query context, and SQL query execution result.")


class JudgeSchema(BaseModel):
    """Judge if the genereated query is suitable for execution or not"""

    answer:Literal['Yes','No']=Field(...,description="Judge if the genereated query is suitable for execution or not,just tell Yes if its safe otherwise No")
    comments:str=Field(...,description="Just additional comments regarding the query")


class ETLAgentSchema(BaseModel):
    """Represent the schema for the ETL Agent"""
    messages:Annotated[list[BaseMessage], add_messages]=Field(...,description="the message list to be processed by the etl agent")


class RouterSchema(BaseModel):
    answer:Literal['sql','etl']=Field(...,description="This the router that will decide wheather to go to sql agent or etl analyst agent based on the user question")
    comments:str=Field(...,description="Additional comments upon the decision")

class DataAgentState(BaseModel):
    messages:Annotated[list[BaseMessage], add_messages]=Field(...,description="the message list to be processed by the data_agent")
    routerResponse:Literal['etl','sql']|None=Field(default=None,description="The router response for understading where actually the flow needs to route")
    generated_sql_query:str|None=Field(default=None, description="The generated query in case of sql node")