from utils.llm_pick import llm_pick
from Models.schema import AgentState
from utils.database import DatabaseUtils
import os
from dotenv import load_dotenv
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
load_dotenv()

def curated_question(state: AgentState)-> AgentState:
    """
    Generates a curated question based on the original user question and the agent's state.

    Args:
        state (AgentState): The current state of the agent, containing the original user question and other relevant information.

    Returns:
        str: The curated question generated by the agent.
    """
    
    # Pick the appropriate LLM based on the desired level
    llm = llm_pick("low")  # You can change the level to "low", "medium", or "high" as needed

    # Use the LLM to generate a curated question based on the original user question
    curated_question_response = llm.invoke(f"Please generate a curated question based on the following user question: {state.user_question}")

    # Extract the curated question from the LLM's response
    state.curated_question = curated_question_response.content.strip()
    state.messages=[HumanMessage(content=curated_question)]

    return state


def prompt_query_context(state:AgentState)->AgentState:
    """Generate a SQL query that will be used to run on the database directly"""
    db_config={
        'host' : os.getenv("host"),
        'port' : os.getenv("port"),
        'user' : os.getenv("user"),
        'password' : os.getenv("password"),
        'database' : os.getenv("database")
    }
    db_obj=DatabaseUtils(db_config)
    schema_info=db_obj.schema_details("public")

    curated_question=state.curated_question

    prompt = f"""
    You are an SQL analyst agent. Your task is to convert the user's natural language 
    query into Postgres SQL query that can be executed on the database. You are provided 
    with the user's original query and the schema details of the database, including
    table names, column names, data types, and sample data for each table so that 
    you can understand the structure of the database and generate an accurate SQL query.
    Unless user explicitly asks for specific number of rows, always limit the output to 10 rows.
    Note - Just generate the SQL query without any explanation or additional text because
    this query will be executed directly on the database. So, the output should be SQL
    ready to be executed without any modifications.  
    
    User's Original Query: {curated_question}

    Database Schema Details:
    {schema_info}
    
    """    

    llm=llm_pick("medium")

    response = llm.invoke(prompt)
    state.generated_sql_query = response.content.strip()

    state.sql_query_execution_result=db_obj.run_sql_query(state.generated_sql_query)

    # print(state)
    return state
    



# # Create the graph
# graph = StateGraph(AgentState)

# # Add nodes
# graph.add_node("curated_question", curated_question)
# graph.add_node("prompt_query_context", prompt_query_context)

# # Define workflow
# graph.add_edge(START, "curated_question")
# graph.add_edge("curated_question", "prompt_query_context")
# graph.add_edge("prompt_query_context", END)

# # Compile
# app = graph.compile()


# # Invoke
# initial_state = AgentState(
#     user_question="Show me the top 10 customers based on total payments"
# )

# result = app.invoke(initial_state)

# print(result)