from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentState(BaseModel):
    """
    Represents the state of an agent in the system.
    """
    messages: Annotated[list, add] = Field(..., description="A list of messages to be used by the agent.")
    user_question: str = Field(..., description="The original user question that the agent will respond to.")
    curated_question:str = Field(..., description="A curated user question that the agent will use to generate a response.")
    prompt_query_context:str = Field(..., description="Detailed prompt with sql query context to be used by the agent for generating a response.")

    is_safe:Literal["Yes", "No"] = Field(..., description="Indicates whether the agent's response is safe or not. Possible values are 'Yes' or 'No'.")
    comments:str=Field(...,description="Comments for the query generated")
    generated_sql_query:str = Field(..., description="The SQL query generated by the agent based on the curated question and prompt query context.")
    sql_query_execution_result:str = Field(..., description="The result of executing the generated SQL query.")
    final_answer:str = Field(..., description="The final answer generated by the agent after processing the curated question, prompt query context, and SQL query execution result.")


class JudgeSchema(BaseModel):
    """Judge if the genereated query is suitable for execution or not"""

    answer:Literal['Yes','No']=Field(...,description="Judge if the genereated query is suitable for execution or not,just tell Yes if its safe otherwise No")
    comments:str=Field(...,description="Just additional comments regarding the query")